/*
 * Catalogo BaluStore
 *
 * Per aggiungere un prodotto:
 * 1. copia l'immagine WebP in assets/products/;
 * 2. copia uno degli oggetti qui sotto;
 * 3. sostituisci i dati e aggiungi il link TikTok Shop reale, se disponibile.
 *
 * Categorie iniziali: "pokemon", "onepiece", "dragonball".
 * Stati ammessi: "available", "coming", "live-only", "sold-out".
 */
window.BALU_PRODUCTS = [
  {
    id: "gem-pack-vol-6",
    name: "Pokémon Gem Pack Vol. 6",
    category: "pokemon",
    type: "box",
    image: "assets/products/pokemon-gem-pack-vol-6-box.webp",
    imageAlt: "Booster Box Pokémon Gem Pack Vol. 6 in cinese semplificato",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmSfw6afVq-6uRTx/",
    featured: true,
    order: 1,
    active: true
  },
  {
    id: "box-primordial-arts-blastoise",
    name: "Pokémon Primordial Arts – Torrent (Blastoise) Booster Box",
    category: "pokemon",
    type: "box",
    image: "assets/products/pokemon-primordial-arts-box-blastoise.webp",
    imageAlt: "Booster Box Pokémon Primordial Arts Torrent con Blastoise",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmAJbHn27d-8n84D/",
    featured: true,
    order: 2,
    active: true
  },
  {
    id: "box-primordial-arts-venusaur",
    name: "Pokémon Primordial Arts – Overgrow (Venusaur) Booster Box",
    category: "pokemon",
    type: "box",
    image: "assets/products/pokemon-primordial-arts-box-venusaur.webp",
    imageAlt: "Booster Box Pokémon Primordial Arts Overgrow con Venusaur",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmSEy3SmK8-cEYs2/",
    featured: true,
    order: 3,
    active: true
  },
  {
    id: "box-terastal-gathering",
    name: "Pokémon Terastal Gathering – Booster Box",
    category: "pokemon",
    type: "box",
    image: "assets/products/pokemon-terastal-gathering-box.webp",
    imageAlt: "Booster Box Pokémon Terastal Gathering in cinese semplificato",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmA8y9EGuW-akzh2/",
    featured: false,
    order: 4,
    active: true
  },
  {
    id: "box-chasing-glory-together",
    name: "Pokémon 共逐荣光 (Chasing Glory Together) – Booster Box",
    category: "pokemon",
    type: "box",
    image: "assets/products/pokemon-chasing-glory-together-box.webp",
    imageAlt: "Booster Box Pokémon Chasing Glory Together in cinese semplificato",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmS4j3ckSM-fPlh3/",
    featured: false,
    order: 5,
    active: true
  },
  {
    id: "box-151-vol-3-slim",
    name: "Pokémon 151 Vol. 3 – Slim Booster Box",
    category: "pokemon",
    type: "box",
    image: "assets/products/pokemon-151-vol-3-slim-box.webp",
    imageAlt: "Slim Booster Box Pokémon 151 Vol. 3 in cinese semplificato",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmA2tquyxn-F1Yr2/",
    featured: false,
    order: 6,
    active: true
  },
  {
    id: "box-storm-emeralda",
    name: "Pokémon Storm Emeralda – Booster Box",
    category: "pokemon",
    type: "box",
    image: "assets/products/pokemon-storm-emeralda-display.webp",
    imageAlt: "Booster Box giapponese Pokémon Storm Emeralda",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmSmNKEVYn-P9UaU/",
    featured: false,
    order: 7,
    active: true
  },
  {
    id: "etb-fiamme-spettrali",
    name: "Pokémon Megaevoluzione – Fiamme Spettrali: Set Allenatore Fuoriclasse",
    category: "pokemon",
    type: "etb",
    image: "assets/products/pokemon-fiamme-spettrali-etb.webp",
    imageAlt: "Set Allenatore Fuoriclasse Pokémon Megaevoluzione Fiamme Spettrali",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmSsVp2bHe-O8zYX/",
    featured: false,
    order: 8,
    active: true
  },
  {
    id: "etb-buio-pesto",
    name: "Pokémon Megaevoluzione – Buio Pesto: Set Allenatore Fuoriclasse",
    category: "pokemon",
    type: "etb",
    image: "assets/products/pokemon-buio-pesto-etb.webp",
    imageAlt: "Set Allenatore Fuoriclasse Pokémon Megaevoluzione Buio Pesto",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmAFD3cXhj-G2yxl/",
    featured: false,
    order: 9,
    active: true
  },
  {
    id: "booster-bundle-fiamme-spettrali",
    name: "Pokémon Megaevoluzione – Fiamme Spettrali: Confezione da 6 buste",
    category: "pokemon",
    type: "booster-bundle",
    image: "assets/products/pokemon-fiamme-spettrali-booster-bundle-6-buste.webp",
    imageAlt: "Confezione da sei buste Pokémon Megaevoluzione Fiamme Spettrali",
    status: "sold-out",
    badge: "Novità",
    tiktokUrl: null,
    featured: false,
    order: 10,
    active: true
  },
  {
    id: "booster-primordial-arts-blastoise",
    name: "Pokémon Primordial Arts – Torrent (Blastoise): busta da 25 carte",
    category: "pokemon",
    type: "booster-pack",
    image: "assets/products/pokemon-primordial-arts-busta-blastoise.webp",
    imageAlt: "Busta da 25 carte Pokémon Primordial Arts Torrent con Blastoise",
    status: "sold-out",
    badge: "Novità",
    tiktokUrl: null,
    featured: false,
    order: 11,
    active: true
  },
  {
    id: "booster-primordial-arts-venusaur",
    name: "Pokémon Primordial Arts – Overgrow (Venusaur): busta da 25 carte",
    category: "pokemon",
    type: "booster-pack",
    image: "assets/products/pokemon-primordial-arts-busta-venusaur.webp",
    imageAlt: "Busta da 25 carte Pokémon Primordial Arts Overgrow con Venusaur",
    status: "sold-out",
    badge: "Novità",
    tiktokUrl: null,
    featured: false,
    order: 12,
    active: true
  },
  {
    id: "booster-storm-emeralda",
    name: "Pokémon Storm Emeralda – Busta",
    category: "pokemon",
    type: "booster-pack",
    image: "assets/products/pokemon-storm-emeralda-busta-rayquaza.webp",
    imageAlt: "Busta giapponese Pokémon Storm Emeralda con Rayquaza",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmSBRa3apV-T3qNX/",
    featured: false,
    order: 13,
    active: true
  },
  {
    id: "booster-bundle-storm-emeralda",
    name: "Pokémon Storm Emeralda – Bundle da 2 buste",
    category: "pokemon",
    type: "booster-bundle",
    image: "assets/products/pokemon-storm-emeralda-doppia-busta.webp",
    imageAlt: "Bundle da due buste giapponesi Pokémon Storm Emeralda",
    status: "available",
    badge: "Novità",
    tiktokUrl: null,
    featured: false,
    order: 14,
    active: true
  },
  {
    id: "booster-bundle-storm-emeralda-3-buste",
    name: "Pokémon Storm Emeralda – Bundle da 3 buste",
    category: "pokemon",
    type: "booster-bundle",
    image: "assets/products/pokemon-storm-emeralda-bundle-3-buste.webp",
    imageAlt: "Bundle da tre buste giapponesi Pokémon Storm Emeralda",
    status: "available",
    badge: "Novità",
    tiktokUrl: null,
    featured: false,
    order: 15,
    active: true
  },
  {
    id: "booster-evoluzioni-eteree-duraludon",
    name: "Pokémon Spada e Scudo – Evoluzioni Eteree: busta artwork Duraludon",
    category: "pokemon",
    type: "booster-pack",
    image: "assets/products/pokemon-evoluzioni-eteree-busta-duraludon.webp",
    imageAlt: "Busta Pokémon Evoluzioni Eteree con artwork di Duraludon",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmS3QQw3cg-hKGC0/",
    featured: false,
    order: 16,
    active: true
  },
  {
    id: "booster-evoluzioni-eteree-sylveon",
    name: "Pokémon Spada e Scudo – Evoluzioni Eteree: busta artwork Sylveon",
    category: "pokemon",
    type: "booster-pack",
    image: "assets/products/pokemon-evoluzioni-eteree-busta-sylveon.webp",
    imageAlt: "Busta Pokémon Evoluzioni Eteree con artwork di Sylveon",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmSHonAsmk-DMaB8/",
    featured: false,
    order: 17,
    active: true
  },
  {
    id: "booster-evoluzioni-eteree-umbreon",
    name: "Pokémon Spada e Scudo – Evoluzioni Eteree: busta artwork Umbreon",
    category: "pokemon",
    type: "booster-pack",
    image: "assets/products/pokemon-evoluzioni-eteree-busta-umbreon.webp",
    imageAlt: "Busta Pokémon Evoluzioni Eteree con artwork di Umbreon",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmSn23Uu6V-WuluP/",
    featured: false,
    order: 18,
    active: true
  },
  {
    id: "booster-evoluzioni-eteree-rayquaza",
    name: "Pokémon Spada e Scudo – Evoluzioni Eteree: busta artwork Rayquaza",
    category: "pokemon",
    type: "booster-pack",
    image: "assets/products/pokemon-evoluzioni-eteree-busta-rayquaza.webp",
    imageAlt: "Busta Pokémon Evoluzioni Eteree con artwork di Rayquaza",
    status: "available",
    badge: "Novità",
    tiktokUrl: "https://vm.tiktok.com/ZN9BmSqWUxtc3-mJisp/",
    featured: false,
    order: 19,
    active: true
  }
];
